#!/usr/bin/env python3
"""
Zen Den — Report Email Delivery

Sends PDF reports as email attachments via SMTP (Gmail App Password)
or Gmail API (OAuth). Includes a styled HTML body with a performance summary.

Usage:
    from report_mailer import send_report_email
    send_report_email(pdf_bytes, client_name, recipients, email_config)
"""

import json
import smtplib
import ssl
from datetime import datetime
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import sys as _sys

def _data_dir():
    if getattr(_sys, '_MEIPASS', None):
        d = Path.home() / "Library" / "Application Support" / "ZenDen"
        d.mkdir(parents=True, exist_ok=True)
        return d
    return Path(__file__).parent

SCHEDULES_PATH = _data_dir() / "report_schedules.json"


def load_schedules():
    if SCHEDULES_PATH.exists():
        with open(SCHEDULES_PATH) as f:
            return json.load(f)
    return {
        "schedules": [],
        "email_config": {
            "method": "smtp",
            "smtp_host": "smtp.gmail.com",
            "smtp_port": 587,
            "sender_email": "",
            "sender_name": "Zen Den",
            "app_password": "",
        },
    }


def save_schedules(data):
    with open(SCHEDULES_PATH, "w") as f:
        json.dump(data, f, indent=2)


def _build_html_body(client_name, date_range, summary=None):
    """Build a styled HTML email body with performance summary."""
    now = datetime.now().strftime("%B %d, %Y")
    summary_rows = ""
    if summary:
        for key, val in summary.items():
            summary_rows += f'<tr><td style="padding:8px 16px;color:#5c5f7a;font-size:13px;border-bottom:1px solid #ede7e0">{key}</td><td style="padding:8px 16px;font-weight:700;font-size:13px;border-bottom:1px solid #ede7e0;text-align:right">{val}</td></tr>'

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;background:#f5f0eb">
<div style="max-width:600px;margin:0 auto;padding:40px 20px">
  <div style="background:#1a2236;border-radius:16px;padding:40px 32px;text-align:center;margin-bottom:24px">
    <div style="font-size:36px;margin-bottom:8px">🧘</div>
    <h1 style="color:#c4b5fd;font-size:24px;margin:0 0 6px;font-weight:800">{client_name}</h1>
    <p style="color:#9ca3c0;font-size:14px;margin:0">Performance Report — {date_range}</p>
    <p style="color:#6b7394;font-size:12px;margin:8px 0 0">Generated {now}</p>
  </div>
  <div style="background:#fff;border-radius:16px;padding:28px 32px;border:1px solid #ede7e0;margin-bottom:24px">
    <h2 style="color:#2d3047;font-size:16px;margin:0 0 6px">📄 Report Attached</h2>
    <p style="color:#5c5f7a;font-size:13px;line-height:1.6;margin:0 0 16px">The full PDF report is attached to this email. Here's a quick overview:</p>
    {f'<table style="width:100%;border-collapse:collapse;margin-bottom:8px">{summary_rows}</table>' if summary_rows else ''}
    <p style="color:#8b8ea8;font-size:11.5px;margin:16px 0 0;font-style:italic">This report was auto-generated by Zen Den. Data sourced from Google Ads.</p>
  </div>
  <div style="text-align:center;padding:16px">
    <p style="color:#8b8ea8;font-size:11px;margin:0">Prepared by Zen Den</p>
    <p style="color:#b0afc8;font-size:10px;margin:4px 0 0">Confidential — do not distribute externally</p>
  </div>
</div>
</body>
</html>"""


def send_report_email(pdf_bytes, client_name, date_range, recipients, email_config, summary=None):
    """Send a report email with PDF attachment via SMTP.

    Args:
        pdf_bytes: bytes of the PDF file
        client_name: e.g. "Solara Skincare"
        date_range: e.g. "Last 30 Days"
        recipients: list of email addresses
        email_config: dict with smtp_host, smtp_port, sender_email, sender_name, app_password
        summary: optional dict of metric_name -> value for the email body

    Returns:
        (success: bool, message: str)
    """
    if not recipients:
        return False, "No recipients specified"

    sender_email = email_config.get("sender_email", "")
    sender_name = email_config.get("sender_name", "Zen Den")
    app_password = email_config.get("app_password", "")
    smtp_host = email_config.get("smtp_host", "smtp.gmail.com")
    smtp_port = int(email_config.get("smtp_port", 587))

    if not sender_email or not app_password:
        return False, "Email not configured — add sender email and app password in Settings"

    safe_name = client_name.replace(" ", "_").lower()
    filename = f"{safe_name}_report_{datetime.now().strftime('%Y%m%d')}.pdf"
    subject = f"{client_name} — Performance Report ({date_range})"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = f"{sender_name} <{sender_email}>"
    msg["To"] = ", ".join(recipients)

    html_body = _build_html_body(client_name, date_range, summary)
    msg.attach(MIMEText(html_body, "html"))

    pdf_part = MIMEApplication(pdf_bytes, _subtype="pdf")
    pdf_part.add_header("Content-Disposition", "attachment", filename=filename)
    msg.attach(pdf_part)

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls(context=context)
            server.login(sender_email, app_password)
            server.sendmail(sender_email, recipients, msg.as_string())
        return True, f"Sent to {len(recipients)} recipient(s)"
    except smtplib.SMTPAuthenticationError:
        return False, "Authentication failed — check email and app password"
    except Exception as e:
        return False, str(e)


def build_summary_from_client(client_data):
    """Build a summary dict from client campaign data for the email body."""
    campaigns = client_data.get("campaigns", [])
    active = [c for c in campaigns if c.get("status", "").upper() != "REMOVED"]
    perf = [c for c in active if c.get("performance")]

    tot_cost = sum(c["performance"].get("cost", 0) for c in perf)
    tot_conv = sum(c["performance"].get("conversions", 0) for c in perf)
    tot_val = sum(c["performance"].get("conv_value", 0) for c in perf)
    tot_clicks = sum(c["performance"].get("clicks", 0) for c in perf)
    tot_impr = sum(c["performance"].get("impressions", 0) for c in perf)
    roas = (tot_val / tot_cost) if tot_cost > 0 else 0

    def fmt_money(n):
        return f"${n:,.2f}" if n < 10000 else f"${n/1000:.1f}K"

    def fmt_num(n):
        return f"{n:,.0f}" if n < 10000 else f"{n/1000:.1f}K"

    return {
        "Campaigns": f"{sum(1 for c in active if c.get('status','').upper()=='ENABLED')} active / {len(active)} total",
        "Total Spend": fmt_money(tot_cost),
        "Impressions": fmt_num(tot_impr),
        "Clicks": fmt_num(tot_clicks),
        "Conversions": fmt_num(tot_conv),
        "Revenue": fmt_money(tot_val),
        "ROAS": f"{roas:.2f}x",
    }


def check_schedule_due(schedule_entry):
    """Check if a schedule entry is due to send right now.

    Returns True if the report should be sent based on frequency and last_sent.
    """
    if not schedule_entry.get("enabled", False):
        return False

    now = datetime.now()
    last_sent = schedule_entry.get("last_sent")
    frequency = schedule_entry.get("frequency", "biweekly")
    target_day = schedule_entry.get("day_of_week", "monday").lower()
    target_time = schedule_entry.get("time", "09:00")

    days_map = {"monday": 0, "tuesday": 1, "wednesday": 2, "thursday": 3, "friday": 4, "saturday": 5, "sunday": 6}
    target_dow = days_map.get(target_day, 0)

    if now.weekday() != target_dow:
        return False

    try:
        hour, minute = map(int, target_time.split(":"))
    except ValueError:
        hour, minute = 9, 0

    if not (hour == now.hour and abs(now.minute - minute) <= 5):
        return False

    if last_sent:
        try:
            last_dt = datetime.fromisoformat(last_sent)
            days_since = (now - last_dt).days
        except (ValueError, TypeError):
            days_since = 999
    else:
        days_since = 999

    intervals = {"daily": 1, "weekly": 7, "biweekly": 14, "monthly": 28}
    min_interval = intervals.get(frequency, 14)

    return days_since >= (min_interval - 1)
